### ISSUE TITLE
file-size-histogram

### ISSUE THREAD

**Issue by farseerfc** [farseerfc/farseerfc.github.io#96]
This issue is reserved for https://farseerfc.me/file-size-histogram.html

**Comment by Aloxaf** [comment]
![](https://fars.ee/Pm2j.webp)
1.46K……还有一堆 64～128K 的文件
我应该好好清理一下了……

**Comment by lilydjwg** [comment]
farseerfc 好棒～

我家刚好 4K 多一点呢：

![myhome](https://user-images.githubusercontent.com/440661/84462077-a3bc6880-aca0-11ea-890d-c17f7f95083b.png)

然而根就只有 2K 了：

![root](https://user-images.githubusercontent.com/440661/84462092-b0d95780-aca0-11ea-988c-698f17b3b3cc.png)

存了许多源码仓库、iso 镜像、视频文件的 xfs 才 1.6K：

![xfs](https://user-images.githubusercontent.com/440661/84462259-204f4700-aca1-11ea-905d-1e905d2d8356.png)

缓存目录好多好小的文件啊：

![cache](https://user-images.githubusercontent.com/440661/84462142-d5353400-aca0-11ea-8f17-d2b68ba2d30e.png)

**Comment by farseerfc** [comment]
百合的系統裏有好多 32~64 的小文件呀，我這兒還沒這麼多……是 rust 編譯結果之類的麼

**Comment by lilydjwg** [comment]
啊对，那个地方有一堆 rust 的编译中间产物。

**Comment by Si-Huan** [comment]
![](https://fars.ee/LH1O.png)
1.38K 感觉在我家里面高峰过早的出现了  
512~1G 的大概是存的番剧，大于 1G 的就是一些 .iso 了

**Comment by MatheMatrix** [comment]
我这里貌似是典型的 4K：

![weiw myhome](https://user-images.githubusercontent.com/4859413/84517614-1dd10980-ad02-11ea-96fc-c8c53ef2558c.png)

**Comment by cuihaoleo** [comment]
我自己家目录是典型的4K。给两个特殊的。

USTC 镜像站可通过 rsync 访问的全部文件：
![repo](https://user-images.githubusercontent.com/889871/85629577-fe51af00-b626-11ea-96c0-ced59c30945f.png)

我们实验室计算集群，所有用户家目录的文件（除了程序和各种程序生成的文件，大部分是图片音频数据）：
![public](https://user-images.githubusercontent.com/889871/85629655-1a555080-b627-11ea-8370-e240f87fedde.png)

**Comment by farseerfc** [comment]
2020年6月25日(木) 6:33 CUI Hao <notifications@github.com>:

> 我自己家目录是典型的4K。给两个特殊的。
>
> USTC 镜像站可通过 rsync 访问的全部文件：
>
>
哇 USTC mirror 有 50T 的數據量了！


> 我们实验室计算集群，所有用户家目录的文件（除了程序和各种程序生成的文件，大部分是图片音频数据）：
>

有好多 1~32 的呢，看來畫圖的時候合併 1~32 的數據在一組也不是很合適，破壞曲線形狀了。

-- 

----------------------------------------------
大阪大学国際公共政策研究科
楊 嘉晨 (YANG Jiachen)
〒560-0043豊中市待兼山町1-7
E-mail： yang@osipp.osaka-u.ac.jp
TEL：080-3853-2770
-----------------------------------------------

**Comment by yichangshengwu** [comment]
说明系统文件又碎又多！！！ （逃跑

**Comment by Hexhu** [comment]
我的家目录:
![my-home-file-size-histogram](https://user-images.githubusercontent.com/13915793/87260563-68f84c80-c467-11ea-991d-420ad654fd89.png)

一堆源码, 音乐和漫画 :3

**Comment by yingziwu** [comment]
根目录下的结果：
![root](https://user-images.githubusercontent.com/22741471/89389036-66021c00-d6f4-11ea-95a7-865c6d9183da.png)

家目录下的结果，这应该是缓存文件比较多
![home](https://user-images.githubusercontent.com/22741471/89389237-b4171f80-d6f4-11ea-9ec1-6779bcfc6ba4.png)

**Comment by poscat0x04** [comment]
![root](https://user-images.githubusercontent.com/53291983/90633577-dc585f80-e258-11ea-8fd8-8a818dde72ea.png)
symlinks

**Comment by farseerfc** [comment]
> ![root](https://user-images.githubusercontent.com/53291983/90633577-dc585f80-e258-11ea-8fd8-8a818dde72ea.png)
> symlinks
> the total file size tho...


是把 /proc/kcore 算進去了嗎，還有這麼多 0 大小的… find 可以 -xdev

**Comment by yingziwu** [comment]
@farseerfc 
> > ![root](https://user-images.githubusercontent.com/53291983/90633577-dc585f80-e258-11ea-8fd8-8a818dde72ea.png)
> > symlinks
> > the total file size tho...
> 
> 是把 /proc/kcore 算進去了嗎，還有這麼多 0 大小的… find 可以 -xdev

应该是把 `/proc` 算进去了。
感觉博文中的find命令可以更新一下：
```bash
find / -type f -not -path '/tmp/*' -not -path '/sys/*' -not -path '/dev/*' -not -path '/proc/*' -not -path '/run/*' -not -path '/media/*' -not -path '*/lost+found/*' -printf "%s %p\n" > /tmp/root.txt
```

**Comment by poscat0x04** [comment]
> > ![root](https://user-images.githubusercontent.com/53291983/90633577-dc585f80-e258-11ea-8fd8-8a818dde72ea.png)
> > symlinks
> > the total file size tho...
> 
> 是把 /proc/kcore 算進去了嗎，還有這麼多 0 大小的… find 可以 -xdev

应该都是 nix 产生的 symlink (传统艺能)

**Comment by poly000** [comment]
![图片](https://user-images.githubusercontent.com/34085039/108157585-10381300-711e-11eb-927a-ce75571e7db2.png)
我的学习资料……

**Comment by nicholascw** [comment]
![图片](https://user-images.githubusercontent.com/7414442/108610301-4b467a80-739a-11eb-8e4c-9c9d4cf49b3f.png)

**Comment by forliuyifei** [comment]
```
$ ./filesizehistogram.py myhome.txt
Traceback (most recent call last):
  File "./filesizehistogram.py", line 38, in <module>
    data=np.array([int(x.split(' ')[0]) for fn in filenames for x in open(fn)])
  File "./filesizehistogram.py", line 38, in <listcomp>
    data=np.array([int(x.split(' ')[0]) for fn in filenames for x in open(fn)])
ValueError: invalid literal for int() with base 10: '请输入密码\n'
```

**Comment by farseerfc** [comment]
> ```
> $ ./filesizehistogram.py myhome.txt
> Traceback (most recent call last):
>   File "./filesizehistogram.py", line 38, in <module>
>     data=np.array([int(x.split(' ')[0]) for fn in filenames for x in open(fn)])
>   File "./filesizehistogram.py", line 38, in <listcomp>
>     data=np.array([int(x.split(' ')[0]) for fn in filenames for x in open(fn)])
> ValueError: invalid literal for int() with base 10: '请输入密码\n'
> ```

你看下 myhome.txt 的內容，感覺不太對吶，“請輸入密碼”是啥。
正常應該是每行一個數字和文件名，空格隔開，文件名可選。

**Comment by forliuyifei** [comment]
> > ```
> > $ ./filesizehistogram.py myhome.txt
> > Traceback (most recent call last):
> >   File "./filesizehistogram.py", line 38, in <module>
> >     data=np.array([int(x.split(' ')[0]) for fn in filenames for x in open(fn)])
> >   File "./filesizehistogram.py", line 38, in <listcomp>
> >     data=np.array([int(x.split(' ')[0]) for fn in filenames for x in open(fn)])
> > ValueError: invalid literal for int() with base 10: '请输入密码\n'
> > ```
> 
> 你看下 myhome.txt 的內容，感覺不太對吶，“請輸入密碼”是啥。
> 正常應該是每行一個數字和文件名，空格隔開，文件名可選。

明白了，因为有个目录需要 root 权限，所以 find 之前加了 sudo ，myhome.txt 第一行多出了：“请输入密码” 🤣

**Comment by forliuyifei** [comment]
![image](https://user-images.githubusercontent.com/53306807/113467122-847f0980-9473-11eb-95e8-fe32d1c36738.png)
/home 目录, 我这里是 2k ?

**Comment by WhiredPlanck** [comment]
![Figure_1.png](https://fars.ee/Cob5.png)

学生党的 /home，有数不清的课件、截图、慕课啥啥啥，还有一些 git 源码 …… QwQ

**Comment by soda92** [comment]
![图片](https://user-images.githubusercontent.com/24788699/121481302-91cdec80-c9fe-11eb-8e75-44ea2be45612.png)

**Comment by sgkoishi** [comment]
![files](https://user-images.githubusercontent.com/9637711/124371319-71780300-dc35-11eb-9bfd-c2131478f3ce.png)
~~一只Windows上的文件~~
没有太多头绪为什么会有这些奇怪的突起.jpg

**Comment by h3fang** [comment]
去掉了/proc, /sys这些
```
sudo find / /home -xdev -type f -printf "%s\n" > data.txt
```
![file_size](https://user-images.githubusercontent.com/1715589/124546811-c26a4000-de5d-11eb-9d3b-6ad0fb0ac6ec.png)

**Comment by liyewen521** [comment]
哈哈，差不多也符合统计值4K了，就是均值有一点大，达到了1.68M，可能因为我生成的大的log文件比较多。
![image](https://fars.ee/V6Hq.jpg)

**Comment by SamLukeYes** [comment]
![nix-store](https://user-images.githubusercontent.com/12882091/186719575-06eebace-76ee-4f8f-a535-1dea26eb92fa.png)
扫了一下我的 `/nix/store`，好像把硬链接全都重复算了，实际占用只有不到 50G

**Comment by Sinofine** [comment]
![图片](https://user-images.githubusercontent.com/47494321/186721800-975ad00e-f956-4775-9ccf-2a6f14b2fa0a.png)
emm 硬连接?我的硬盘加起来也只有1.5T喵

**Comment by illyber** [comment]
涨知识了。很有趣的研究
